services:
  prowjack:
    build: .
    container_name: prowjack
    restart: unless-stopped
    network_mode: "service:protonvpn"
 #   networks:
 #     - no_vpn
 #   ports:
 #     - "7014:7014"
    env_file:
      - ./.env
    volumes:
      - /run/media/vinicius/L/torrents:/data             # ← compartilhado com qBittorrent





